spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/app
    username: root
    password: 1234567890
    driver-class-name: com.mysql.jdbc.Driver